# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
#export JAVA_HOME="$(/usr/libexec/java_home)"

# cd to the path of the front Finder window
cdf() {
    target=`osascript -e 'tell application "Finder" to if (count of Finder windows) > 0 then get POSIX path of (target of front Finder window as text)'`
    if [ "$target" != "" ]; then
        cd "$target"; pwd
    else
        echo 'No Finder window found' >&2
        cd ~/Desktop
    fi
}

#alias twistd="twistd -no web --path=."
alias mongod="mongod --config /usr/local/etc/mongod.conf"
alias wgetmirror="wget -E -H -k -K -p "
alias wgetreq="wget -p -k"
alias nmap="nmap -T4 -A -v"
alias v="mvim"
alias htop="sudo htop"
alias g="git"
alias gs="git status"
alias gp="git pull"
alias gpush="git push"
alias gl="git log"
alias gc="git commit"
alias ga="git add"
alias gcheck="git checkout"
alias gd="git diff"
alias gdc="git diff --cached"
alias gb="git branch"
alias gr="git remote -v"
alias py="pyenv versions"
export EDITOR=/usr/bin/mvim
export PYTHONSTARTUP=$HOME/.pythonrc


ZSH_THEME=""

COMPLETION_WAITING_DOTS="true"

plugins=(brew pip python zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh


export PATH=${PATH}:~/DevLocal/pebble-dev/PebbleSDK-3.0-dp9/bin

source /usr/local/opt/autoenv/activate.sh
export PATH="/usr/local/sbin:$PATH"

eval "$(pyenv init -)"
